// Generated by llvm2cpp - DO NOT MODIFY!


GlobalVariable* makeLLVMVariable(Module *mod) {

// Type Definitions
ArrayType* ArrayTy_2 = ArrayType::get(IntegerType::get(mod->getContext(), 64), 128);

ArrayType* ArrayTy_1 = ArrayType::get(ArrayTy_2, 1024);

PointerType* PointerTy_0 = PointerType::get(ArrayTy_1, 0);


// Constant Definitions
ConstantAggregateZero* const_array_3 = ConstantAggregateZero::get(ArrayTy_1);

GlobalVariable* gvar_array_active_pps = new GlobalVariable(/*Module=*/*mod, 
/*Type=*/ArrayTy_1,
/*isConstant=*/false,
/*Linkage=*/GlobalValue::InternalLinkage,
/*Initializer=*/0, // has initializer, specified below
/*Name=*/"active_pps");
gvar_array_active_pps->setAlignment(16);
gvar_array_active_pps->setInitializer(const_array_3);
return gvar_array_active_pps;
}
