// Generated by llvm2cpp - DO NOT MODIFY!


GlobalVariable* makeLLVMVariable(Module *mod) {

// Type Definitions
StructType *StructTy_struct_timespec = mod->getTypeByName("struct.timespec");
if (!StructTy_struct_timespec) {
StructTy_struct_timespec = StructType::create(mod->getContext(), "struct.timespec");
}
std::vector<Type*>StructTy_struct_timespec_fields;
StructTy_struct_timespec_fields.push_back(IntegerType::get(mod->getContext(), 64));
StructTy_struct_timespec_fields.push_back(IntegerType::get(mod->getContext(), 64));
if (StructTy_struct_timespec->isOpaque()) {
StructTy_struct_timespec->setBody(StructTy_struct_timespec_fields, /*isPacked=*/false);
}

ArrayType* ArrayTy_2 = ArrayType::get(StructTy_struct_timespec, 128);

ArrayType* ArrayTy_1 = ArrayType::get(ArrayTy_2, 1024);

PointerType* PointerTy_0 = PointerType::get(ArrayTy_1, 0);


// Constant Definitions
ConstantAggregateZero* const_array_3 = ConstantAggregateZero::get(ArrayTy_1);

GlobalVariable* gvar_array_duration_check_pp_nos = new GlobalVariable(/*Module=*/*mod, 
/*Type=*/ArrayTy_1,
/*isConstant=*/false,
/*Linkage=*/GlobalValue::InternalLinkage,
/*Initializer=*/0, // has initializer, specified below
/*Name=*/"duration_check_pp_nos");
gvar_array_duration_check_pp_nos->setAlignment(16);
gvar_array_duration_check_pp_nos->setInitializer(const_array_3);
return gvar_array_duration_check_pp_nos;
}
