// Generated by llvm2cpp - DO NOT MODIFY!


GlobalVariable* makeLLVMVariable(Module *mod) {

// Type Definitions
ArrayType* ArrayTy_1 = ArrayType::get(IntegerType::get(mod->getContext(), 64), 128);

PointerType* PointerTy_0 = PointerType::get(ArrayTy_1, 0);


// Constant Definitions
ConstantAggregateZero* const_array_2 = ConstantAggregateZero::get(ArrayTy_1);

GlobalVariable* gvar_array_trust_pp_nos = new GlobalVariable(/*Module=*/*mod, 
/*Type=*/ArrayTy_1,
/*isConstant=*/false,
/*Linkage=*/GlobalValue::InternalLinkage,
/*Initializer=*/0, // has initializer, specified below
/*Name=*/"trust_pp_nos");
gvar_array_trust_pp_nos->setAlignment(16);
gvar_array_trust_pp_nos->setInitializer(const_array_2);
return gvar_array_trust_pp_nos;
}
